In [1]:
import tensorflow as tf
import numpy as np

/home/artem/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [ ]:
inputtensor = tf.constant([[1,2,3],[3,4,5]], shape=[2,3], verify_shape=True)
print(inputtensor)

#### Copy matrix with all zeros

In [16]:
all_zeros = tf.zeros_like(inputtensor)
print(all_zeros)

Tensor("zeros_like_8:0", shape=(2, 3), dtype=int32)


#### Create matrix with all ones

In [19]:
all_ones = tf.ones([2,4], "int32")
print(all_ones)

Tensor("ones_1:0", shape=(2, 4), dtype=int32)


#### Any others

In [21]:
print(tf.fill([3,3], 3.5))

Tensor("Fill_1:0", shape=(3, 3), dtype=float32)


#### Creating tensors with sequenses

In [29]:
#start, stop, num
print(tf.linspace(5.0,15.0,3))
print(np.linspace(5.0,15.0,3))
#start, end, delta
print(tf.range(3,9,2))


Tensor("LinSpace_6:0", shape=(3,), dtype=float32)
[  5.  10.  15.]
Tensor("range_2:0", shape=(3,), dtype=int32)


#### Randomly generated constants

In [3]:
# from IPython.display import Image
# Image(filename='./img/for_jupyter/randomConstTF.png')

In [34]:
#use seed to "safe" ramdomness
tf.set_random_seed(0) #any seed val

#### Variables

In [4]:
# from IPython.display import Image
# Image(filename='./img/for_jupyter/variables.png')

In [40]:
#to initialize all variables
init = tf.global_variables_initializer()# can specifie which variables to initialize
with tf.Session() as sess:
    sess.run(init)

In [46]:
#another way
w = tf.Variable(tf.ones([3,4]))
with tf.Session() as sess:
    sess.run(w.initializer)
    print(w.eval())

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [2]:
#assign stuff
w = tf.Variable(tf.ones([3,4]))
assign_op = w.assign(tf.zeros([3,4]))
with tf.Session() as sess:
    sess.run(w.initializer)
    print(w.eval())
    sess.run(assign_op)
    print(w.eval())

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


#### Control Dependancies

In [ ]:
#if have a,b,c nodes... can verefy siquence by:
with g.control_dependencies([a,b,c])

#### Placeholders